export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE";

export const FETCH_IMAGES_REQUEST = "FETCH_IMAGES_REQUEST";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";

export const DOWNLOAD_IMAGES_REQUEST = 'DOWNLOAD_IMAGES_REQUEST';
export const DOWNLOAD_IMAGES_SUCCESS = 'DOWNLOAD_IMAGES_SUCCESS';
export const DOWNLOAD_IMAGES_FAILURE = 'DOWNLOAD_IMAGES_FAILURE';

export const REMOVE_IMAGES_REQUEST = 'REMOVE_IMAGES_REQUEST';
export const REMOVE_IMAGES_SUCCESS = 'REMOVE_IMAGES_SUCCESS';
export const REMOVE_IMAGES_FAILURE = 'REMOVE_IMAGES_FAILURE';
